import type { Metadata } from "next";
import {Header} from "@/components/Header/Header"
import "./globals.css";
import { Montserrat } from '@next/font/google';

const montserrat = Montserrat({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.0/font/bootstrap-icons.min.css"
        />
      </head>
      <body className={montserrat.className}>
        <Header /> 
        {children}
      </body>
    </html>
  );
}
